export const SET_ELEMENTS = "SET_ELEMENTS";
export const SET_ELEMENT  = "SET_ELEMENT";
export const SET_ELEMENTS_DEPS = "SET_ELEMENTS_DEPS";
export const SET_ELEMENT_SHAPES = "SET_ELEMENT_SHAPES";
export const UPDATED_ELEMENTS = "UPDATED_ELEMENTS";
export const DELETED_ELEMENT  = "DELETED_ELEMENT";

export const SET_DEFAULT_ELEMENT_ID = "SET_DEFAULT_ELEMENT_ID";


// ------------------- BRAND NEW! ---------------------------------------

export const GET_CURRENT_ELEMENT = "GET_CURRENT_ELEMENT";
export const GET_CURRENT_ELEMENTS = "GET_CURRENT_ELEMENTS";
export const GET_CHILDREN = "GET_CHILDREN";
export const GET_CONNECTIONS = "GET_CONNECTIONS";
export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const GET_ORDERED_COLLECTIONS = "GET_ORDERED_COLLECTIONS";
export const GET_ELEMENT_SHAPES = "GET_ELEMENT_SHAPES";


export const SET_DICTS = "SET_DICTS";
export const SET_CURRENT_ELEMENT = "SET_CURRENT_ELEMENT";
export const SET_CURRENT_ELEMENT_ID = "SET_CURRENT_ELEMENT_ID";
