export const SCENARIO_SET = 'SCENARIO_SET'
export const SCENARIO_ROOT_SET = 'SCENARIO_ROOT_SET'

export const ELEMENTS_SET = 'ELEMENTS_SET'
export const ELEMENTS_SELECT = 'ELEMENTS_SELECT'
export const ELEMENTS_SET_CURRENT = 'ELEMENTS_SET_CURRENT'
export const ELEMENTS_CLEAR = 'ELEMENTS_CLEAR'

export const REFERENCES_SET = 'REFERENCES_SET'

export const SHAPES_ADD_SINGLE = 'SHAPES_ADD_SINGLE'
export const SHAPES_ADD = 'SHAPES_ADD'
export const SHAPES_CLEAR = 'SHAPES_CLEAR'

export const UI_INFOBOX_SET = 'UI_INFOBOX_SET'
