export const SET_ELEMENTS = "SET_ELEMENTS";
export const SET_ELEMENT  = "SET_ELEMENT";
export const UPDATED_ELEMENTS = "UPDATED_ELEMENTS";
export const DELETED_ELEMENT  = "DELETED_ELEMENT";

export const SET_CURRENT_ELEMENT = "SET_CURRENT_ELEMENT";
