export const SET_ELEMENTS = "SET_ELEMENTS";
export const SET_ELEMENT  = "SET_ELEMENT";
export const SET_ELEMENTS_DEPS = "SET_ELEMENTS_DEPS";
export const UPDATED_ELEMENTS = "UPDATED_ELEMENTS";
export const DELETED_ELEMENT  = "DELETED_ELEMENT";

export const SET_CURRENT_ELEMENT = "SET_CURRENT_ELEMENT";
export const SET_DEFAULT_ELEMENT = "SET_DEFAULT_ELEMENT";
export const SET_DICTS = "SET_DICTS";
